<?php
return CMap::mergeArray(
	require('main.php'),
	array(
		'name'=>'More Than Vacation',
		'modules'=>array(
			'admin'=>array(),
		),'import'=>array(
			'application.extensions.yii-mail.*',
		),'components'=>array(
			'user'=>array(
				// enable cookie-based authentication
				'allowAutoLogin'=>true,
				'loginUrl'=>array('site/login'),
			),
			'mail' => array(
				'class' => 'application.extensions.yii-mail.YiiMail',
				'transportType' => 'php',
				'viewPath' => 'application.views.mail',
				'logging' => true,
				'dryRun' => false
			),
			'urlManager'=>array(
				'rules'=>array(
					'home'=>array('site/index')
				),
			),
		),
		'params'=>array(
			'salt' => 'justforvegetarian',
			'adminEmail'=>'webmaster@example.com',
			'organization_name'=>'',
			'yiimailType'=>'php',
			'adminEmail'=>'admin@mail.com',
			'noreplyEmail'=>'noreply@mail.com',
			'fb'=>array(
				'appid'=>'203396579765915',
				'appsec'=>'f31fee519dd01004d3821d982726638e',
				'permission'=>array(
					'scope'=>'email,user_photos,user_birthday',
					'redirect_uri' => 'http://www.morethanvacation.com/'
				),
			),'paging'=> array(
				'pageSize'=>20,
				'nextPageLabel'=>'Next',
				'prevPageLabel'=>'Prev',
				'firstPageLabel'=>'&lt;&lt;',
				'lastPageLabel'=>'&gt;&gt;',
				'header'=>'',
				'cssFile'=>false,
			),'flag'=>array(
				'gender'=>array(
					'M'=>'Male',
					'F'=>'Female',
				),'status'=>array(
					'1'=>'Pending',
					'2'=>'Publish',
				),'category_status'=>array(
					'0'=>'Pending',
					'1'=>'Publish',
				),'navigation_type'=>array(
					'1'=>'Link',
					'2'=>'Content',
				),'yesNo'=>array(
					'0'=>'No',
					'1'=>'Yes'
				),'lang'=>array(
					'1'=>'中文',
					'2'=>'English',
					'3'=>'Malay',
					'4'=>'Other',
				),'link_type_id'=>array(
					'1'=>'Same',
					'2'=>'Translate'
				)
			),'adminnav'=>array(
				'items'=>array(
					array(
						'label'=>'Developer',
						'url'=>'#',
						'itemOptions'=>array('class'=>''),
						'linkOptions'=>array('class'=>'clickfalse'),
						'items'=>array(
							array(
								'label'=>'Hook',
								'url'=>array('/admin/user/search'),
							)
						),
					),array(
						'itemOptions'=>array('class'=>'sprt'),
						'template'=>'',
					),array(
						'label'=>'Super Admin',
						'url'=>'#',
						'itemOptions'=>array('class'=>''),
						'linkOptions'=>array('class'=>'clickfalse'),
						'items'=>array(
							array(
								'label'=>'User',
								'url'=>array('/admin/user/search'),
							)
						),
					),array(
						'itemOptions'=>array('class'=>'sprt'),
						'template'=>'',
					),array(
						'label'=>'Admin',
						'url'=>'#',
						'itemOptions'=>array('class'=>''),
						'linkOptions'=>array('class'=>'clickfalse'),
						'items'=>array(
							array(
								'label'=>'Category',
								'url'=>array('/admin/category/create'),
							),array(
								'label'=>'Flag',
								'url'=>array('/admin/flag/search'),
							),array(
								'label'=>'Navigation',
								'url'=>array('/admin/navigation/search'),
							),
						),
					),array(
						'itemOptions'=>array('class'=>'sprt'),
						'template'=>'',
					),array(
						'label'=>'Editor',
						'url'=>'#',
						'itemOptions'=>array('class'=>''),
						'linkOptions'=>array('class'=>'clickfalse'),
						'items'=>array(
							array(
								'label'=>'Canvas',
								'url'=>array('/admin/canvas/search'),
							)
						),
					),array(
						'itemOptions'=>array('class'=>'sprt'),
						'template'=>'',
					),
				),
			),'country'=>array(
				'AF'=>"Afghanistan",
				'AX'=>"Aland Islands",
				'AL'=>"Albania",
				'DZ'=>"Algeria",
				'AS'=>"American Samoa",
				'AD'=>"Andorra",
				'AO'=>"Angola",
				'AI'=>"Anguilla",
				'AQ'=>"Antarctica",
				'AG'=>"Antigua and Barbuda",
				'AR'=>"Argentina",
				'AM'=>"Armenia",
				'AW'=>"Aruba",
				'AP'=>"Asia/Pacific Region",
				'AU'=>"Australia",
				'AT'=>"Austria",
				'AZ'=>"Azerbaijan",
				'BS'=>"Bahamas",
				'BH'=>"Bahrain",
				'BD'=>"Bangladesh",
				'BB'=>"Barbados",
				'BY'=>"Belarus",
				'BE'=>"Belgium",
				'BZ'=>"Belize",
				'BJ'=>"Benin",
				'BM'=>"Bermuda",
				'BT'=>"Bhutan",
				'BO'=>"Bolivia",
				'BA'=>"Bosnia and Herzegovina",
				'BW'=>"Botswana",
				'BV'=>"Bouvet Island",
				'BR'=>"Brazil",
				'IO'=>"British Indian Ocean Territory",
				'BN'=>"Brunei",
				'BG'=>"Bulgaria",
				'BF'=>"Burkina Faso",
				'BI'=>"Burundi",
				'KH'=>"Cambodia",
				'CM'=>"Cameroon",
				'CA'=>"Canada",
				'CV'=>"Cape Verde",
				'KY'=>"Cayman Islands",
				'CF'=>"Central African Republic",
				'TD'=>"Chad",
				'CL'=>"Chile",
				'CN'=>"China",
				'CX'=>"Christmas Island",
				'CC'=>"Cocos Islands",
				'CO'=>"Colombia",
				'KM'=>"Comoros",
				'CG'=>"Congo",
				'CD'=>"Congo, the Democratic Republic of the",
				'CK'=>"Cook Islands",
				'CR'=>"Costa Rica",
				'CI'=>"Cote d'Ivoire",
				'HR'=>"Croatia",
				'CU'=>"Cuba",
				'CY'=>"Cyprus",
				'CZ'=>"Czech Republic",
				'DK'=>"Denmark",
				'DJ'=>"Djibouti",
				'DM'=>"Dominica",
				'DO'=>"Dominican Republic",
				'TP'=>"East Timor",
				'EC'=>"Ecuador",
				'EG'=>"Egypt",
				'SV'=>"El Salvador",
				'GQ'=>"Equatorial Guinea",
				'ER'=>"Eritrea",
				'EE'=>"Estonia",
				'ET'=>"Ethiopia",
				'FK'=>"Falkland Islands",
				'FO'=>"Faroe Islands",
				'FJ'=>"Fiji",
				'FI'=>"Finland",
				'FR'=>"France",
				'FX'=>"France, Metropolitan",
				'GF'=>"French Guiana",
				'PF'=>"French Polynesia",
				'TF'=>"French Southern Territories",
				'GA'=>"Gabon",
				'GM'=>"Gambia",
				'GE'=>"Georgia",
				'DE'=>"Germany",
				'GH'=>"Ghana",
				'GI'=>"Gibraltar",
				'GR'=>"Greece",
				'GL'=>"Greenland",
				'GD'=>"Grenada",
				'GP'=>"Guadeloupe",
				'GU'=>"Guam",
				'GT'=>"Guatemala",
				'GG'=>"Guernsey",
				'GN'=>"Guinea",
				'GW'=>"Guinea Bissau",
				'GY'=>"Guyana",
				'HT'=>"Haiti",
				'HM'=>"Heard and McDonald Islands",
				'HN'=>"Honduras",
				'VA'=>"Honduras",
				'HK'=>"Hong Kong",
				'HU'=>"Hungary",
				'IS'=>"Iceland",
				'IN'=>"India",
				'ID'=>"Indonesia",
				'IR'=>"Iran",
				'IQ'=>"Iraq",
				'IE'=>"Ireland",
				'IM'=>"Isle of Man",
				'IL'=>"Israel",
				'IT'=>"Italy",
				'JM'=>"Jamaica",
				'JP'=>"Japan",
				'JE'=>"Jersey",
				'JO'=>"Jordan",
				'KZ'=>"Kazakhstan",
				'KE'=>"Kenya",
				'KI'=>"Kiribati",
				'KP'=>"Korea, Democratic People's Republic of",
				'KR'=>"Korea, Republic of",
				'KW'=>"Kuwait",
				'KG'=>"Kyrgyzstan",
				'LA'=>"Laos",
				'LV'=>"Latvia",
				'LB'=>"Lebanon",
				'LS'=>"Lesotho",
				'LR'=>"Liberia",
				'LY'=>"Libya",
				'LI'=>"Liechtenstein",
				'LT'=>"Lithuania",
				'LU'=>"Luxembourg",
				'MO'=>"Macau",
				'MK'=>"Macedonia Former Yugoslav Republic",
				'MG'=>"Madagascar",
				'MW'=>"Malawi",
				'MY'=>"Malaysia",
				'MV'=>"Maldives",
				'ML'=>"Mali",
				'MT'=>"Malta",
				'MH'=>"Marshall Islands",
				'MQ'=>"Martinique",
				'MR'=>"Mauritania",
				'MU'=>"Mauritius",
				'YT'=>"Mayotte",
				'MX'=>"Mexico",
				'FM'=>"Micronesia Federated States of",
				'MD'=>"Moldova",
				'MC'=>"Monaco",
				'MN'=>"Mongolia",
				'ME'=>"Montenegro",
				'MS'=>"Montserrat",
				'MA'=>"Morocco",
				'MZ'=>"Mozambique",
				'MM'=>"Myanmar",
				'NA'=>"Namibia",
				'NR'=>"Nauru",
				'NP'=>"Nepal",
				'NL'=>"Netherlands",
				'AN'=>"Netherlands Antilles",
				'NC'=>"New Caledonia",
				'NZ'=>"New Zealand",
				'NI'=>"Nicaragua",
				'NE'=>"Niger",
				'NG'=>"Nigeria",
				'NU'=>"Niue",
				'NF'=>"Norfolk Island",
				'MP'=>"Northern Mariana Islands",
				'NO'=>"Norway",
				'OM'=>"Oman",
				'PK'=>"Others",
				'PW'=>"Pakistan",
				'PS'=>"Palau",
				'PA'=>"Panama",
				'PG'=>"Papua New Guinea",
				'PY'=>"Paraguay",
				'PE'=>"Peru",
				'PH'=>"Philippines",
				'PN'=>"Pitcairn Island",
				'PL'=>"Poland",
				'PT'=>"Portugal",
				'PR'=>"Puerto Rico",
				'QA'=>"Qatar",
				'RE'=>"Reunion",
				'RO'=>"Romania",
				'RU'=>"Russia",
				'RW'=>"Rwanda",
				'KN'=>"Saint Kitts Nevis",
				'LC'=>"Saint Lucia",
				'VC'=>"Saint Vincent and The Grenadines",
				'WS'=>"Samoa",
				'SM'=>"San Marino",
				'ST'=>"Sao Tome and Principe",
				'SA'=>"Saudi Arabia",
				'SN'=>"Senegal",
				'RS'=>"Serbia",
				'SC'=>"Seychelles",
				'SL'=>"Sierra Leone",
				'SG'=>"Singapore",
				'SK'=>"Slovakia",
				'SI'=>"Slovenia",
				'SB'=>"Solomon Islands",
				'SO'=>"Somalia",
				'ZA'=>"South Africa",
				'GS'=>"South Georgia and S Sandwich Islands",
				'ES'=>"Spain",
				'LK'=>"Sri Lanka",
				'SH'=>"St Helena",
				'PM'=>"St Pierre and Miquelon",
				'SD'=>"Sudan",
				'SR'=>"Suriname",
				'SJ'=>"Svalbard and Jan Mayen Islands",
				'SZ'=>"Swaziland",
				'SE'=>"Sweden",
				'CH'=>"Switzerland",
				'SY'=>"Syria",
				'TW'=>"Taiwan",
				'TJ'=>"Tajikistan",
				'TZ'=>"Tanzania",
				'TH'=>"Thailand",
				'TG'=>"Togo",
				'TK'=>"Tokelau",
				'TO'=>"Tonga",
				'TT'=>"Trinidad and Tobago",
				'TN'=>"Tunisia",
				'TR'=>"Turkey",
				'TM'=>"Turkmenistan",
				'TC'=>"Turks and Caicos Islands",
				'TV'=>"Tuvalu",
				'UG'=>"Uganda",
				'UA'=>"Ukraine",
				'AE'=>"United Arab Emirates",
				'GB'=>"United Kingdom",
				'UM'=>"United States Minor Outlying Islands",
				'US'=>"United States of America",
				'UY'=>"Uruguay",
				'UZ'=>"Uzbekistan",
				'VU'=>"Vanuatu",
				'VE'=>"Venezuela",
				'VN'=>"Vietnam",
				'VG'=>"Virgin Islands (British)",
				'VI'=>"Virgin Islands (U.S.)",
				'WF'=>"Wallis and Futuna Islands",
				'EH'=>"Western Sahara",
				'YE'=>"Yemen",
				'YU'=>"Yugoslavia",
				'ZM'=>"Zambia",
				'ZW'=>"Zimbabwe",
			),
		),
	)
);

?>